using ZeroAlloc.Serialisation;

namespace ZeroAlloc.Scheduling;

/// <summary>
/// AOT-safe <see cref="IJobSerializer"/> implementation that delegates to an
/// <see cref="ISerializerDispatcher"/> generated by <c>ZeroAlloc.Serialisation</c>.
/// </summary>
/// <remarks>
/// Register by annotating your job types with <c>[ZeroAllocSerializable]</c> in the
/// consuming assembly and calling <c>services.AddSerializerDispatcher()</c> before
/// <c>AddScheduling()</c>. When an <see cref="ISerializerDispatcher"/> is present in
/// the DI container, <c>AddScheduling</c> automatically uses this class instead of the
/// reflection-based <see cref="DefaultJobSerializer"/>.
/// </remarks>
public sealed class DispatchingJobSerializer : IJobSerializer
{
    private readonly ISerializerDispatcher _dispatcher;

    /// <summary>Initializes a new <see cref="DispatchingJobSerializer"/>.</summary>
    public DispatchingJobSerializer(ISerializerDispatcher dispatcher)
    {
        _dispatcher = dispatcher ?? throw new ArgumentNullException(nameof(dispatcher));
    }

    /// <inheritdoc/>
    public byte[] Serialize<T>(T job) where T : notnull
    {
        var memory = _dispatcher.Serialize(job, typeof(T));
        // ReadOnlyMemory<byte> → byte[]: the dispatcher already allocated a buffer via
        // ArrayBufferWriter<byte>; we copy to a plain array so IJobStore implementations
        // that persist raw byte[] (EfCore, Redis) receive an ordinary heap array.
        return memory.ToArray();
    }

    /// <inheritdoc/>
    public T Deserialize<T>(byte[] payload) where T : notnull
    {
        var result = _dispatcher.Deserialize(new ReadOnlyMemory<byte>(payload), typeof(T));
        return result is T typed
            ? typed
            : throw new InvalidOperationException(
                $"Deserializing {typeof(T).Name} returned null or wrong type.");
    }
}
