using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Globalization;
using System.Text;

namespace ZeroAlloc.Scheduling.Generator;

internal static class SchedulingCodeWriter
{
    public static void Write(SourceProductionContext ctx, JobModel model)
    {
        var sb = new StringBuilder();
        var typeFqn = $"global::{model.TypeFqn}";
        var executorName = $"{model.TypeName}JobTypeExecutor";
        var diMethodName = $"Add{model.TypeName}Job";
        var startupName = $"{model.TypeName}RecurringStartup";

        AppendHeader(sb, model.Namespace);

        if (!model.IsMediatorBridge)
            AppendExecutor(sb, executorName, typeFqn, model.TypeFqn, model.MaxAttempts);

        if (model.IsRecurring)
            AppendRecurringStartup(sb, model, startupName, typeFqn);

        AppendDiExtension(sb, diMethodName, executorName, typeFqn, startupName,
                          model.IsRecurring, model.IsMediatorBridge);

        var hint = model.Namespace != null
            ? $"{model.Namespace}_{model.TypeName}.Scheduling.g.cs"
            : $"{model.TypeName}.Scheduling.g.cs";

        ctx.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void AppendHeader(StringBuilder sb, string? ns)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine("using Microsoft.Extensions.Options;");
        sb.AppendLine("using ZeroAlloc.Scheduling;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
    }

    private static void AppendExecutor(StringBuilder sb, string executorName, string typeFqn, string jobFqn, int maxAttempts)
    {
        sb.AppendLine($"internal sealed class {executorName} : global::ZeroAlloc.Scheduling.IJobTypeExecutor");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::ZeroAlloc.Scheduling.IJobSerializer _serializer;");
        sb.AppendLine($"    public {executorName}(global::ZeroAlloc.Scheduling.IJobSerializer serializer) => _serializer = serializer;");
        sb.AppendLine($"    public string TypeName => \"{jobFqn}\";");
        sb.AppendLine($"    public int MaxAttempts => {maxAttempts.ToString(CultureInfo.InvariantCulture)};");
        sb.AppendLine("    public async global::System.Threading.Tasks.ValueTask ExecuteAsync(");
        sb.AppendLine("        byte[] payload,");
        sb.AppendLine("        global::ZeroAlloc.Scheduling.JobContext ctx,");
        sb.AppendLine("        global::System.Threading.CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var job = _serializer.Deserialize<{typeFqn}>(payload);");
        sb.AppendLine("        await job.ExecuteAsync(ctx, ct).ConfigureAwait(false);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendRecurringStartup(StringBuilder sb, JobModel model, string startupName, string typeFqn)
    {
        var cronLiteral = model.CronExpression != null
            ? $"\"{model.CronExpression}\""
            : $"global::ZeroAlloc.Scheduling.EveryToCron.Convert(global::ZeroAlloc.Scheduling.{model.EveryValue})";

        var maxAttemptsExpr = model.MaxAttempts > 0
            ? model.MaxAttempts.ToString(CultureInfo.InvariantCulture)
            : "_options.Value.DefaultMaxAttempts";

        sb.AppendLine($"internal sealed class {startupName} : global::Microsoft.Extensions.Hosting.IHostedService");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::ZeroAlloc.Scheduling.IJobStore _store;");
        sb.AppendLine("    private readonly global::ZeroAlloc.Scheduling.IJobSerializer _serializer;");
        sb.AppendLine("    private readonly global::Microsoft.Extensions.Options.IOptions<global::ZeroAlloc.Scheduling.SchedulingOptions> _options;");
        sb.AppendLine($"    public {startupName}(global::ZeroAlloc.Scheduling.IJobStore store, global::ZeroAlloc.Scheduling.IJobSerializer serializer, global::Microsoft.Extensions.Options.IOptions<global::ZeroAlloc.Scheduling.SchedulingOptions> options)");
        sb.AppendLine("    { _store = store; _serializer = serializer; _options = options; }");
        AppendStartAsyncBody(sb, model.TypeFqn, typeFqn, cronLiteral, maxAttemptsExpr);
        sb.AppendLine("    public global::System.Threading.Tasks.Task StopAsync(global::System.Threading.CancellationToken ct) => global::System.Threading.Tasks.Task.CompletedTask;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendStartAsyncBody(StringBuilder sb, string jobFqn, string typeFqn, string cronLiteral, string maxAttemptsExpr)
    {
        sb.AppendLine("    public async global::System.Threading.Tasks.Task StartAsync(global::System.Threading.CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var cron = {cronLiteral};");
        sb.AppendLine("        var expr = global::Cronos.CronExpression.Parse(cron, global::Cronos.CronFormat.Standard);");
        sb.AppendLine("        var next = expr.GetNextOccurrence(global::System.DateTimeOffset.UtcNow, global::System.TimeZoneInfo.Utc);");
        sb.AppendLine("        if (next is null) return;");
        sb.AppendLine($"        var maxAttempts = {maxAttemptsExpr};");
        sb.AppendLine($"        var payload = _serializer.Serialize(new {typeFqn}());");
        sb.AppendLine($"        await _store.UpsertRecurringAsync(\"{jobFqn}\", payload, next.Value, cron, maxAttempts, ct).ConfigureAwait(false);");
        sb.AppendLine("    }");
    }

    private static void AppendDiExtension(StringBuilder sb, string diMethodName, string executorName,
        string typeFqn, string startupName, bool isRecurring, bool isMediatorBridge)
    {
        sb.AppendLine("public static partial class SchedulingServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static global::ZeroAlloc.Scheduling.ISchedulingBuilder {diMethodName}(");
        sb.AppendLine("        this global::ZeroAlloc.Scheduling.ISchedulingBuilder builder)");
        sb.AppendLine("    {");

        if (isMediatorBridge)
        {
            sb.AppendLine($"        builder.Services.AddTransient<global::ZeroAlloc.Scheduling.IJobTypeExecutor, global::ZeroAlloc.Scheduling.Mediator.MediatorJobTypeExecutor<{typeFqn}>>();");
        }
        else
        {
            sb.AppendLine($"        builder.Services.AddTransient<global::ZeroAlloc.Scheduling.IJobTypeExecutor, {executorName}>();");
        }

        if (isRecurring)
            sb.AppendLine($"        builder.Services.AddHostedService<{startupName}>();");
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    [global::System.Obsolete(\"Use AddScheduling().{diMethodName}() instead. Will be removed in the next major.\", DiagnosticId = \"ZASCH010\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode(\"AddScheduling may register DefaultJobSerializer which uses reflection-based JSON. Call services.AddSerializerDispatcher() first for AOT-safe serialisation.\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode(\"AddScheduling may register DefaultJobSerializer which may require runtime code generation. Call services.AddSerializerDispatcher() first for AOT-safe serialisation.\")]");
        sb.AppendLine($"    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {diMethodName}(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddScheduling().{diMethodName}();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}
